#!/bin/sh
COMMIT=`git rev-parse HEAD`
mkdir -p gen/nl/sense_os/service/
echo "/* Automatically generated by versioninfo.sh */\npackage nl.sense_os.service;\n public class VersionInfo {\n\tpublic static String commit = \"$COMMIT\";\n}"> gen/nl/sense_os/service/VersionInfo.java
