var searchData=
[
  ['databasehandler',['DatabaseHandler',['../interfacenl_1_1sense__os_1_1datastorageengine_1_1_database_handler.html',1,'nl::sense_os::datastorageengine']]],
  ['databasehandlerexception',['DatabaseHandlerException',['../classnl_1_1sense__os_1_1datastorageengine_1_1_database_handler_exception.html',1,'nl::sense_os::datastorageengine']]],
  ['dataconsumer',['DataConsumer',['../interfacenl_1_1sense__os_1_1service_1_1subscription_1_1_data_consumer.html',1,'nl::sense_os::service::subscription']]],
  ['datapoint',['DataPoint',['../classnl_1_1sense__os_1_1datastorageengine_1_1_data_point.html',1,'nl::sense_os::datastorageengine']]],
  ['datapoint',['DataPoint',['../classnl_1_1sense__os_1_1service_1_1constants_1_1_sensor_data_1_1_data_point.html',1,'nl::sense_os::service::constants::SensorData']]],
  ['dataproducer',['DataProducer',['../interfacenl_1_1sense__os_1_1service_1_1subscription_1_1_data_producer.html',1,'nl::sense_os::service::subscription']]],
  ['datatransmithandler',['DataTransmitHandler',['../classnl_1_1sense__os_1_1service_1_1commonsense_1_1senddata_1_1_data_transmit_handler.html',1,'nl::sense_os::service::commonsense::senddata']]],
  ['datatransmitter',['DataTransmitter',['../classnl_1_1sense__os_1_1service_1_1_data_transmitter.html',1,'nl::sense_os::service']]],
  ['datatype',['DataType',['../enumnl_1_1sense__os_1_1service_1_1shared_1_1_sensor_data_point_1_1_data_type.html',1,'nl::sense_os::service::shared::SensorDataPoint']]],
  ['dbhelper',['DbHelper',['../classnl_1_1sense__os_1_1service_1_1provider_1_1_local_storage_sql_1_1_db_helper.html',1,'nl::sense_os::service::provider::LocalStorageSql']]],
  ['dbhelper',['DbHelper',['../classnl_1_1sense__os_1_1service_1_1storage_1_1_db_helper.html',1,'nl::sense_os::service::storage']]],
  ['defaultsensorregistrationservice',['DefaultSensorRegistrationService',['../classnl_1_1sense__os_1_1service_1_1commonsense_1_1_default_sensor_registration_service.html',1,'nl::sense_os::service::commonsense']]],
  ['defaultsensorregistrator',['DefaultSensorRegistrator',['../classnl_1_1sense__os_1_1service_1_1commonsense_1_1_default_sensor_registrator.html',1,'nl::sense_os::service::commonsense']]],
  ['deviceproximity',['DeviceProximity',['../classnl_1_1sense__os_1_1service_1_1deviceprox_1_1_device_proximity.html',1,'nl::sense_os::service::deviceprox']]],
  ['devprox',['DevProx',['../classnl_1_1sense__os_1_1service_1_1constants_1_1_sense_prefs_1_1_main_1_1_dev_prox.html',1,'nl::sense_os::service::constants::SensePrefs::Main']]],
  ['dummyappwidgetservice',['DummyAppWidgetService',['../classnl_1_1sense__os_1_1service_1_1appwidget_1_1_dummy_app_widget_service.html',1,'nl::sense_os::service::appwidget']]]
];
