var namespaces =
[
    [ "com", "namespacecom.html", null ],
    [ "com::phonegap", "namespacecom_1_1phonegap.html", null ],
    [ "com::phonegap::plugins", "namespacecom_1_1phonegap_1_1plugins.html", null ],
    [ "com.phonegap.plugins.sense", "namespacecom_1_1phonegap_1_1plugins_1_1sense.html", "namespacecom_1_1phonegap_1_1plugins_1_1sense" ],
    [ "nl", "namespacenl.html", null ],
    [ "nl::sense_os", "namespacenl_1_1sense__os.html", null ],
    [ "nl.sense_os.service", "namespacenl_1_1sense__os_1_1service.html", "namespacenl_1_1sense__os_1_1service" ],
    [ "nl.sense_os.service.ambience", "namespacenl_1_1sense__os_1_1service_1_1ambience.html", "namespacenl_1_1sense__os_1_1service_1_1ambience" ],
    [ "nl.sense_os.service.appwidget", "namespacenl_1_1sense__os_1_1service_1_1appwidget.html", "namespacenl_1_1sense__os_1_1service_1_1appwidget" ],
    [ "nl.sense_os.service.commonsense", "namespacenl_1_1sense__os_1_1service_1_1commonsense.html", "namespacenl_1_1sense__os_1_1service_1_1commonsense" ],
    [ "nl.sense_os.service.commonsense.senddata", "namespacenl_1_1sense__os_1_1service_1_1commonsense_1_1senddata.html", "namespacenl_1_1sense__os_1_1service_1_1commonsense_1_1senddata" ],
    [ "nl.sense_os.service.configuration", "namespacenl_1_1sense__os_1_1service_1_1configuration.html", "namespacenl_1_1sense__os_1_1service_1_1configuration" ],
    [ "nl.sense_os.service.constants", "namespacenl_1_1sense__os_1_1service_1_1constants.html", "namespacenl_1_1sense__os_1_1service_1_1constants" ],
    [ "nl.sense_os.service.deviceprox", "namespacenl_1_1sense__os_1_1service_1_1deviceprox.html", "namespacenl_1_1sense__os_1_1service_1_1deviceprox" ],
    [ "nl.sense_os.service.external_sensors", "namespacenl_1_1sense__os_1_1service_1_1external__sensors.html", "namespacenl_1_1sense__os_1_1service_1_1external__sensors" ],
    [ "nl.sense_os.service.feedback", "namespacenl_1_1sense__os_1_1service_1_1feedback.html", "namespacenl_1_1sense__os_1_1service_1_1feedback" ],
    [ "nl.sense_os.service.location", "namespacenl_1_1sense__os_1_1service_1_1location.html", "namespacenl_1_1sense__os_1_1service_1_1location" ],
    [ "nl.sense_os.service.motion", "namespacenl_1_1sense__os_1_1service_1_1motion.html", "namespacenl_1_1sense__os_1_1service_1_1motion" ],
    [ "nl.sense_os.service.phonestate", "namespacenl_1_1sense__os_1_1service_1_1phonestate.html", "namespacenl_1_1sense__os_1_1service_1_1phonestate" ],
    [ "nl.sense_os.service.provider", "namespacenl_1_1sense__os_1_1service_1_1provider.html", "namespacenl_1_1sense__os_1_1service_1_1provider" ],
    [ "nl.sense_os.service.push", "namespacenl_1_1sense__os_1_1service_1_1push.html", "namespacenl_1_1sense__os_1_1service_1_1push" ],
    [ "nl.sense_os.service.states", "namespacenl_1_1sense__os_1_1service_1_1states.html", "namespacenl_1_1sense__os_1_1service_1_1states" ],
    [ "nl.sense_os.service.storage", "namespacenl_1_1sense__os_1_1service_1_1storage.html", "namespacenl_1_1sense__os_1_1service_1_1storage" ]
];